apiVersion: v1
kind: Service
metadata:
  name: { { include "microservices-vote-worker.fullname" . } }
  labels: { { include "microservices-vote-worker.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: http
      protocol: TCP
      name: http
  selector:
    { { include "microservices-vote-worker.selectorLabels" . | nindent 4 } }
